services:

  app:
    image: argon/keep-it:dev
    build:
      context: ./app/
      target: dev
    volumes:
      - ./app/:/app/
      - /app/node_modules/
      - /app/.next/
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/
